"""Initial MySQL schema; never deployed before the MySQL architecture switch.

No source imports or rule seeds run in this frozen migration.
"""
from alembic import op
import sqlalchemy as sa
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_classes',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_classes')),
    sa.UniqueConstraint('name', name=op.f('uq_badge_classes_name'))
    )
    op.create_table('courses',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('code', name=op.f('uq_courses_code'))
    )
    op.create_table('import_batches',
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('importer_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("source IN ('engagement','assignment','badge','survey','salesforce')", name=op.f('ck_import_batches_source')),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name=op.f('ck_import_batches_status')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_import_batches_row_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('source', 'file_sha256', 'importer_version', name=op.f('uq_import_batches_source'))
    )
    op.create_table('model_runs',
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('cohort_policy', sa.String(length=32), server_default='intersection', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("cohort_policy = 'intersection'", name=op.f('ck_model_runs_cohort_policy')),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name=op.f('ck_model_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_table('students',
    sa.Column('identity_digest', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('identity_digest', name=op.f('uq_students_identity_digest'))
    )
    op.create_table('assessment_rules',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pass_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active_slot', sa.Integer(), sa.Computed('CASE WHEN enabled THEN 1 ELSE NULL END', persisted=True), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.String(length=200), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("enabled = false OR status = 'confirmed'", name=op.f('ck_assessment_rules_enabled_confirmed')),
    sa.CheckConstraint("status IN ('confirmed','candidate')", name=op.f('ck_assessment_rules_status')),
    sa.CheckConstraint('pass_threshold >= 0 AND pass_threshold <= 100', name=op.f('ck_assessment_rules_threshold')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assessment_rules_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_rules')),
    sa.UniqueConstraint('course_id', 'version', name=op.f('uq_assessment_rules_course_id'))
    )
    op.create_index(op.f('ix_assessment_rules_course_id'), 'assessment_rules', ['course_id'], unique=False)
    op.create_index('uq_assessment_rules_enabled_course', 'assessment_rules', ['course_id', 'active_slot'], unique=True)
    op.create_table('badge_class_course_mapping',
    sa.Column('badge_class_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='manual_review', nullable=False),
    sa.Column('mapping_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("status IN ('confirmed','manual_review')", name=op.f('ck_badge_class_course_mapping_status')),
    sa.ForeignKeyConstraint(['badge_class_id'], ['badge_classes.id'], name=op.f('fk_badge_class_course_mapping_badge_class_id_badge_classes')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_badge_class_course_mapping_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_class_course_mapping')),
    sa.UniqueConstraint('badge_class_id', name=op.f('uq_badge_class_course_mapping_badge_class_id'))
    )
    op.create_index(op.f('ix_badge_class_course_mapping_course_id'), 'badge_class_course_mapping', ['course_id'], unique=False)
    op.create_table('course_offerings',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=120), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('unknown','planned','in_progress','completed')", name=op.f('ck_course_offerings_status')),
    sa.CheckConstraint('ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on', name=op.f('ck_course_offerings_dates')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_offerings_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offerings')),
    sa.UniqueConstraint('source_key', name=op.f('uq_course_offerings_source_key'))
    )
    op.create_index(op.f('ix_course_offerings_course_id'), 'course_offerings', ['course_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("code IN ('invalid_row','missing_required','invalid_date','invalid_number','unmapped_course','ambiguous_offering','duplicate_record','unsupported_source')", name=op.f('ck_import_errors_code')),
    sa.CheckConstraint('`row_number` IS NULL OR `row_number` > 0', name=op.f('ck_import_errors_row_number')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_errors_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_batch_id'), 'import_errors', ['batch_id'], unique=False)
    op.create_table('assignments',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('assessment_key', sa.String(length=32), nullable=True),
    sa.Column('mapping_status', sa.String(length=16), server_default='unverified', nullable=False),
    sa.Column('max_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("mapping_status != 'confirmed' OR assessment_key IS NOT NULL", name=op.f('ck_assignments_confirmed_key')),
    sa.CheckConstraint("mapping_status IN ('unverified','confirmed','manual_review')", name=op.f('ck_assignments_mapping_status')),
    sa.CheckConstraint('max_score IS NULL OR max_score > 0', name=op.f('ck_assignments_max_score')),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], name=op.f('fk_assignments_offering_id_course_offerings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    sa.UniqueConstraint('id', 'offering_id', name=op.f('uq_assignments_id')),
    sa.UniqueConstraint('offering_id', 'source_key', name=op.f('uq_assignments_offering_id'))
    )
    op.create_index(op.f('ix_assignments_offering_id'), 'assignments', ['offering_id'], unique=False)
    op.create_table('badge_awards',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('badge_class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('match_status', sa.String(length=20), server_default='manual_review', nullable=False),
    sa.Column('outcome', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("match_status IN ('matched','missing_student','revoked','manual_review')", name=op.f('ck_badge_awards_match_status')),
    sa.CheckConstraint("outcome != 'achieved' OR (student_id IS NOT NULL AND revoked = false AND offering_id IS NOT NULL AND match_status = 'matched')", name=op.f('ck_badge_awards_eligible_success')),
    sa.CheckConstraint("outcome IN ('unknown','achieved','not_achieved','ineligible')", name=op.f('ck_badge_awards_outcome')),
    sa.CheckConstraint('source_row > 0', name=op.f('ck_badge_awards_source_row')),
    sa.ForeignKeyConstraint(['badge_class_id'], ['badge_classes.id'], name=op.f('fk_badge_awards_badge_class_id_badge_classes')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_badge_awards_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], name=op.f('fk_badge_awards_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_badge_awards_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_awards')),
    sa.UniqueConstraint('batch_id', 'source_row', name=op.f('uq_badge_awards_batch_id'))
    )
    op.create_index(op.f('ix_badge_awards_badge_class_id'), 'badge_awards', ['badge_class_id'], unique=False)
    op.create_index(op.f('ix_badge_awards_batch_id'), 'badge_awards', ['batch_id'], unique=False)
    op.create_index(op.f('ix_badge_awards_offering_id'), 'badge_awards', ['offering_id'], unique=False)
    op.create_index(op.f('ix_badge_awards_student_id'), 'badge_awards', ['student_id'], unique=False)
    op.create_table('engagement_events',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('source_row > 0', name=op.f('ck_engagement_events_source_row')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_engagement_events_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], name=op.f('fk_engagement_events_offering_id_course_offerings')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_engagement_events_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagement_events')),
    sa.UniqueConstraint('batch_id', 'source_row', name=op.f('uq_engagement_events_batch_id'))
    )
    op.create_index(op.f('ix_engagement_events_batch_id'), 'engagement_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_engagement_events_offering_id'), 'engagement_events', ['offering_id'], unique=False)
    op.create_index(op.f('ix_engagement_events_student_id'), 'engagement_events', ['student_id'], unique=False)
    op.create_table('assignment_submissions',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='unknown', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('unknown','missing','submitted','graded','excused')", name=op.f('ck_assignment_submissions_status')),
    sa.CheckConstraint('source_row > 0 AND attempt > 0', name=op.f('ck_assignment_submissions_positive_numbers')),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('fk_assignment_submissions_assignment_id_assignments')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_assignment_submissions_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_assignment_submissions_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_submissions')),
    sa.UniqueConstraint('batch_id', 'source_row', name=op.f('uq_assignment_submissions_batch_id')),
    sa.UniqueConstraint('batch_id', 'student_id', 'assignment_id', 'attempt', name='uq_submissions_batch_student_assignment_attempt')
    )
    op.create_index(op.f('ix_assignment_submissions_assignment_id'), 'assignment_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_batch_id'), 'assignment_submissions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_student_id'), 'assignment_submissions', ['student_id'], unique=False)


def downgrade():
    # Dropping each table also removes its indexes. MySQL forbids dropping
    # indexes that are still required by foreign keys before dropping the table.
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_submissions')
    op.drop_table('engagement_events')
    op.drop_table('badge_awards')
    op.drop_table('assignments')
    op.drop_table('import_errors')
    op.drop_table('course_offerings')
    op.drop_table('badge_class_course_mapping')
    op.drop_table('assessment_rules')
    op.drop_table('students')
    op.drop_table('model_runs')
    op.drop_table('import_batches')
    op.drop_table('courses')
    op.drop_table('badge_classes')
