"""Preserve source observations and offer per-offering assessment rule versions."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
revision = "0002_import_fields"
down_revision = "0001_initial"
branch_labels = None
depends_on = None

def update_checks(new):
    checks = [
        ('assignments', 'ck_assignments_max_score', 'max_score IS NULL OR max_score >= 0' if new else 'max_score IS NULL OR max_score > 0'),
        ('assignment_submissions', 'ck_assignment_submissions_positive_numbers', 'source_row > 0 AND (attempt IS NULL OR attempt > 0)' if new else 'source_row > 0 AND attempt > 0'),
        ('assignment_submissions', 'ck_assignment_submissions_status', "status IN ('unknown','unsubmitted','missing','submitted','graded','excused')" if new else "status IN ('unknown','missing','submitted','graded','excused')"),
    ]
    for table, name, expression in checks:
        op.drop_constraint(op.f(name), table, type_='check')
        op.create_check_constraint(op.f(name), table, expression)


def upgrade():
    update_checks(True)
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_rules', sa.Column('offering_id', sa.Integer(), nullable=True))
    op.add_column('assessment_rules', sa.Column('scope_key', sa.Integer(), sa.Computed('COALESCE(offering_id, 0)', persisted=True), nullable=True))
    op.drop_index('uq_assessment_rules_course_id', table_name='assessment_rules')
    op.drop_index('uq_assessment_rules_enabled_course', table_name='assessment_rules')
    op.create_index('uq_assessment_rules_enabled_course', 'assessment_rules', ['course_id', 'scope_key', 'active_slot'], unique=True)
    op.create_unique_constraint('uq_rules_course_scope_version', 'assessment_rules', ['course_id', 'scope_key', 'version'])
    op.create_foreign_key(op.f('fk_assessment_rules_offering_id_course_offerings'), 'assessment_rules', 'course_offerings', ['offering_id'], ['id'])
    op.add_column('assignment_submissions', sa.Column('missing', sa.Boolean(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('late', sa.Boolean(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('excused', sa.Boolean(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('graded_at', sa.DateTime(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('source_fields', sa.JSON(), nullable=True))
    op.alter_column('assignment_submissions', 'attempt',
               existing_type=mysql.INTEGER(),
               nullable=True, server_default=None,
               existing_server_default=sa.text("'1'"))
    op.add_column('badge_awards', sa.Column('source_fields', sa.JSON(), nullable=True))
    op.add_column('badge_awards', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('engagement_events', sa.Column('times_viewed', sa.Integer(), nullable=True))
    op.add_column('engagement_events', sa.Column('participated_count', sa.Integer(), nullable=True))
    op.add_column('engagement_events', sa.Column('first_viewed_at', sa.DateTime(), nullable=True))
    op.add_column('engagement_events', sa.Column('last_viewed_at', sa.DateTime(), nullable=True))
    op.add_column('engagement_events', sa.Column('source_fields', sa.JSON(), nullable=True))
    op.add_column('import_batches', sa.Column('summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # Refuse lossy reversal once new semantics are in use.
    if not op.get_context().as_sql:
        count = op.get_bind().execute(sa.text("SELECT (SELECT COUNT(*) FROM assignment_submissions) + (SELECT COUNT(*) FROM engagement_events) + (SELECT COUNT(*) FROM badge_awards) + (SELECT COUNT(*) FROM assessment_rules WHERE offering_id IS NOT NULL)")).scalar()
        if count:
            raise RuntimeError("Downgrade requires an empty observation store and no offering rules")
    update_checks(False)
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'summary')
    op.drop_column('engagement_events', 'source_fields')
    op.drop_column('engagement_events', 'last_viewed_at')
    op.drop_column('engagement_events', 'first_viewed_at')
    op.drop_column('engagement_events', 'participated_count')
    op.drop_column('engagement_events', 'times_viewed')
    op.drop_column('badge_awards', 'expires_at')
    op.drop_column('badge_awards', 'source_fields')
    op.alter_column('assignment_submissions', 'attempt',
               existing_type=mysql.INTEGER(),
               nullable=False, server_default=sa.text("'1'"),
               existing_server_default=sa.text("'1'"))
    op.drop_column('assignment_submissions', 'source_fields')
    op.drop_column('assignment_submissions', 'graded_at')
    op.drop_column('assignment_submissions', 'excused')
    op.drop_column('assignment_submissions', 'late')
    op.drop_column('assignment_submissions', 'missing')
    op.drop_constraint(op.f('fk_assessment_rules_offering_id_course_offerings'), 'assessment_rules', type_='foreignkey')
    op.drop_constraint('uq_rules_course_scope_version', 'assessment_rules', type_='unique')
    op.drop_index('uq_assessment_rules_enabled_course', table_name='assessment_rules')
    op.create_index('uq_assessment_rules_enabled_course', 'assessment_rules', ['course_id', 'active_slot'], unique=True)
    op.create_index('uq_assessment_rules_course_id', 'assessment_rules', ['course_id', 'version'], unique=True)
    op.drop_column('assessment_rules', 'scope_key')
    op.drop_column('assessment_rules', 'offering_id')
    # ### end Alembic commands ###
